version: "3.7"

services:
  postgres:
    container_name: loan_database
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=loan
      - POSTGRES_USER=sa_loan
      - POSTGRES_PASSWORD=sa_loan
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  prometheus:
    container_name: loan_prometheus
    image: prom/prometheus
    ports:
      - "8081:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - default

  grafana:
    container_name: loan_grafana
    image: grafana/grafana
    ports:
      - "8082:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - default

volumes:
  postgres-data:
    driver: local
  grafana-data:
    driver: local

networks:
  default:
    driver: bridge